/* config.h.  Generated by configure.  */
/* config.in.  Generated automatically from configure.in by autoheader.  */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you have the <getopt.h> header file.  */
#define HAVE_GETOPT_H 1

/* Name of package */
#define PACKAGE "sidmain"

/* Version number of package */
#define VERSION "0.1"

