/* config.h.  Generated by configure.  */
/* config.in.  Generated automatically from configure.in by autoheader.  */

/* Name of package */
#define PACKAGE "sidsamples"

/* Version number of package */
#define VERSION "0.1"

