/* sidconfutil.h.  Generated by configure.  */
/* sidconfutil.in.  Generated automatically from configure.in by autoheader.  */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you have the strerror function.  */
#define HAVE_STRERROR 1

/* Define if you have the <sstream> header file.  */
#define HAVE_SSTREAM 1

/* Define if you have the <strstream.h> header file.  */
/* #undef HAVE_STRSTREAM_H */

/* Name of package */
#define PACKAGE "sid"

/* Version number of package */
#define VERSION "0.1"

/* Define to disable run-time assert() checking. */
/* #undef NDEBUG */

/* Define if std:: prefix works for <cctype> functions */
#define STD_CCTYPE 1

/* Define if compiler supports __builtin_expect */
#define HAVE_BUILTIN_EXPECT 1

/* Define to build-time exec-prefix */
#define SID_EXEC_PREFIX "/usr/local/sid-1.1"

