/* config.h.  Generated by configure.  */
/* config.in.  Generated automatically from configure.in by autoheader.  */

/* Define if you have the getopt function.  */
#define HAVE_GETOPT 1

/* Define if you have the m library (-lm).  */
#define HAVE_LIBM 1

/* Name of package */
#define PACKAGE "sidcomp"

/* Version number of package */
#define VERSION "0.1"

/* Define to 1 if we found this declaration otherwise define to 0. */
#define HAVE_DECL_VASPRINTF 1

/* Define to 1 if we found this declaration otherwise define to 0. */
#define HAVE_DECL_ASPRINTF 1

/* Define to 1 if we found this declaration otherwise define to 0. */
#define HAVE_DECL_BASENAME 1

/* Define to 1 if we found this declaration otherwise define to 0. */
#define HAVE_DECL_GETOPT 0

