#ifndef CYGONCE_PKGCONF_HAL_ARM_PID_H
#define CYGONCE_PKGCONF_HAL_ARM_PID_H
/*
 * File <pkgconf/hal_arm_pid.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */


#define HAL_PLATFORM_CPU    "ARM 7TDMI"
#define HAL_PLATFORM_BOARD  "PID"
#define HAL_PLATFORM_EXTRA  ""

#define CYGPRI_KERNEL_TESTS_DHRYSTONE_PASSES 100000
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD 38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD_38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 2
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_2
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_0
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 12500
#define CYGNUM_HAL_RTC_PERIOD_12500
#define CYGBLD_GLOBAL_OPTIONS 1
#define CYGTST_SID_FLAGS --board=pid7t -EL

#endif
