/* config.h.  Generated by configure.  */
/* config.in.  Generated automatically from configure.in by autoheader.  */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you have the ctime function.  */
#define HAVE_CTIME 1

/* Define if you have the cygwin_conv_to_full_posix_path function.  */
/* #undef HAVE_CYGWIN_CONV_TO_FULL_POSIX_PATH */

/* Define if you have the <time.h> header file.  */
#define HAVE_TIME_H 1

/* Name of package */
#define PACKAGE "sidcomp"

/* Version number of package */
#define VERSION "0.1"

