/* config.h.  Generated by configure.  */
/* config.in.  Generated automatically from configure.in by autoheader.  */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define if you can safely include both <sys/time.h> and <time.h>.  */
#define TIME_WITH_SYS_TIME 1

/* Define if you have the ftime function.  */
#define HAVE_FTIME 1

/* Define if you have the gettimeofday function.  */
#define HAVE_GETTIMEOFDAY 1

/* Define if you have the inet_addr function.  */
#define HAVE_INET_ADDR 1

/* Define if you have the inet_aton function.  */
#define HAVE_INET_ATON 1

/* Define if you have the sched_yield function.  */
#define HAVE_SCHED_YIELD 1

/* Define if you have the select function.  */
#define HAVE_SELECT 1

/* Define if you have the strtoul function.  */
#define HAVE_STRTOUL 1

/* Define if you have the strtoull function.  */
#define HAVE_STRTOULL 1

/* Define if you have the times function.  */
#define HAVE_TIMES 1

/* Define if you have the usleep function.  */
#define HAVE_USLEEP 1

/* Define if you have the vasprintf function.  */
#define HAVE_VASPRINTF 1

/* Define if you have the vsnprintf function.  */
#define HAVE_VSNPRINTF 1

/* Define if you have the <../ucbinclude/sys/ioctl.h> header file.  */
/* #undef HAVE____UCBINCLUDE_SYS_IOCTL_H */

/* Define if you have the </usr/include/curses.h> header file.  */
/* #undef HAVE__USR_INCLUDE_CURSES_H */

/* Define if you have the <arpa/inet.h> header file.  */
#define HAVE_ARPA_INET_H 1

/* Define if you have the <curses.h> header file.  */
/* #undef HAVE_CURSES_H */

/* Define if you have the <mmsystem.h> header file.  */
/* #undef HAVE_MMSYSTEM_H */

/* Define if you have the <netinet/in.h> header file.  */
#define HAVE_NETINET_IN_H 1

/* Define if you have the <netinet/tcp.h> header file.  */
#define HAVE_NETINET_TCP_H 1

/* Define if you have the <sched.h> header file.  */
#define HAVE_SCHED_H 1

/* Define if you have the <sys/socket.h> header file.  */
#define HAVE_SYS_SOCKET_H 1

/* Define if you have the <sys/time.h> header file.  */
#define HAVE_SYS_TIME_H 1

/* Define if you have the <sys/timeb.h> header file.  */
#define HAVE_SYS_TIMEB_H 1

/* Define if you have the <sys/types.h> header file.  */
#define HAVE_SYS_TYPES_H 1

/* Define if you have the <time.h> header file.  */
#define HAVE_TIME_H 1

/* Define if you have the <unistd.h> header file.  */
#define HAVE_UNISTD_H 1

/* Define if you have the <windows.h> header file.  */
/* #undef HAVE_WINDOWS_H */

/* Define if you have the kernel32 library (-lkernel32).  */
/* #undef HAVE_LIBKERNEL32 */

/* Define if you have the m library (-lm).  */
#define HAVE_LIBM 1

/* Define if you have the stdc++ library (-lstdc++).  */
#define HAVE_LIBSTDC__ 1

/* Define if you have the winmm library (-lwinmm).  */
/* #undef HAVE_LIBWINMM */

/* Name of package */
#define PACKAGE "sidcomp"

/* Version number of package */
#define VERSION "0.1"

/* Define if curses library is usable */
/* #undef HAVE_CURSES_LIBRARY */

/* Define if ISO C99 Features in use */
#define _ISOC99_SOURCE 1

/* Define if GNU extensions in use */
/* #undef _GNU_SOURCE */

/* Define if SVID extensions in use */
#define _SVID_SOURCE 1

/* Define if SVID extensions in use */
#define _BSD_SOURCE 1

/* Define if ftime(3) is declared via sys/timeb.h */
#define HAVE_FTIME_DECL 1

/* Define if usleep(2) via unistd.h */
#define HAVE_USLEEP_DECL 1

/* Define if socklen_t is declared via sys/socket.h */
#define HAVE_SOCKLEN_T 1

