src/ser_16x5x.o.d:  \
 /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/ecos-3.0/packages/devs/serial/generic/16x5x/v3_0/src/ser_16x5x.c \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/pkgconf/system.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/pkgconf/io_serial.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/pkgconf/io_serial_generic_16x5x.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/pkgconf/io_serial_arm_pid.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/pkgconf/io.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/io/io.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/pkgconf/hal.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/pkgconf/hal_arm.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/pkgconf/hal_arm_pid.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/infra/cyg_type.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/stddef.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/gnutools/arm-eabi/bin/../lib/gcc/arm-eabi/4.3.2/include/stddef.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/hal/basetype.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/error/codes.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/pkgconf/error.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/hal/hal_intr.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/hal/hal_platform_ints.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/io/devtab.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/hal/drv_api.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/pkgconf/kernel.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/pkgconf/infra.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/kernel/kapi.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/memalloc/kapi.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/pkgconf/memalloc.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/kernel/kapidata.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/memalloc/kapidata.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/hal/hal_tables.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/hal/hal_arch.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/io/serial.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/io/serialio.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/io/config_keys.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/infra/diag.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/stdarg.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/gnutools/arm-eabi/bin/../lib/gcc/arm-eabi/4.3.2/include/stdarg.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/infra/cyg_ass.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/hal/hal_io.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/hal/plf_io.h \
  /home/adrian/_ETSIT-UPM/BECA-SimAntares/ecos/arm-pid/arm_pid_install/include/cyg/io/arm_arm7_pid_ser.inl
